#root -l -b -q SkimClassification.C+\(\"ZnnH110\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZnnH115\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZnnH120\"\)  >& logSkimClass &
root -l -b -q SkimClassification.C+\(\"ZnnH125\"\)  >& logSkimClassZnnH125 &
#root -l -b -q SkimClassification.C+\(\"ZnnH130\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZnnH135\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"WlnH110\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"WlnH115\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"WlnH120\"\)  >& logSkimClass &
root -l -b -q SkimClassification.C+\(\"WlnH125\"\)  >& logSkimClassWlnH125 &
#root -l -b -q SkimClassification.C+\(\"WlnH130\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"WlnH135\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZllH110\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZllH115\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZllH120\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZllH125\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZllH130\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZllH135\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"WJetsPtW70\"\)  >& logSkimClass &
root -l -b -q SkimClassification.C+\(\"WJets\"\)  >& logSkimClassWJets &
#root -l -b -q SkimClassification.C+\(\"WJetsPtW100\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZJetsPtZ100\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZJetsHT50\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZJetsHT100\"\)  >& logSkimClass &
root -l -b -q SkimClassification.C+\(\"ZJets\"\)  >& logSkimClassZJets &
root -l -b -q SkimClassification.C+\(\"ZJetsHT200\"\)  >& logSkimClassZJetsHT200 &
root -l -b -q SkimClassification.C+\(\"ZJetsHT400\"\)  >& logSkimClassZJetsHT400 &
root -l -b -q SkimClassification.C+\(\"ZJetsHW\"\)  >& logSkimClassZJetsHW &
#root -l -b -q SkimClassification.C+\(\"DYJetsM50\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"DYJetsPtZ70\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"DYJetsPtZ100\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"WW\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"WZ\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"ZZ\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"TTJets\"\)  >& logSkimClass &
root -l -b -q SkimClassification.C+\(\"TTMadv2\"\)  >& logSkimClassTTMadv2 &
root -l -b -q SkimClassification.C+\(\"TTPythia8\"\)  >& logSkimClassTTPythia8 &
#root -l -b -q SkimClassification.C+\(\"T_tW\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"Tbar_tW\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"T_s\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"Tbar_s\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"T_t\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"Tbar_t\"\)  >& logSkimClass &
root -l -b -q SkimClassification.C+\(\"s_Top\"\)  >& logSkimClasss_Top &
#root -l -b -q SkimClassification.C+\(\"QCDPt50\"\)  >& logSkimClass &
root -l -b -q SkimClassification.C+\(\"QCD\"\)  >& logSkimClassQCD &
#root -l -b -q SkimClassification.C+\(\"QCDPt80\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDPt120\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDPt170\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDPt300\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDPt470\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDPt600\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDPt800\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDPt1000\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDPt1400\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDPt1800\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDHT100\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"QCDHT250\"\)  >& logSkimClass &
#root -l -b -q SkimClassification.C+\(\"Data\"\)  >& logSkimClass &
